name = "Mortar2D"
uuid = "0b7cd5e2-b3f3-5fae-9080-a65912ed73e3"
authors = ["Jukka Aho <ahojukka5@gmail.com>"]
version = "0.1.3"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "≥ 1.0"

[extras]
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[targets]
test = ["TimerOutputs"]
