name = "Mortar2D"
uuid = "0b7cd5e2-b3f3-5fae-9080-a65912ed73e3"
authors = ["Jukka Aho <ahojukka5@gmail.com>"]
version = "0.1.3"

[compat]
julia = "≥ 1.0"

[extras]
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[targets]
test = ["TimerOutputs"]
